### PR TITLE
Fix crash due to unnecessary settime on Android phone

### PR DESCRIPTION
**Pull request by eggonlea**
If Android phone is used, both of RC and DS might have already adjusted their time correctly from network. It's not necessary to change it. Furthermore, the latest version of Android doesn't allow this operation without system privileged.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
This bug is already fixed in the next version of the official FTC SDK, and therefore it will be fixed in the next version of OpenRC-Turbo as well. Thanks for the contribution though!

**Comment by eggonlea** [comment]
Cool. Thx! Looking forward to the new SDK release.

**Comment by NoahAndrews** [comment]
Just for the sake of education, I believe this PR would still crash if the RC and DS phones had clocks more than a second off, so that's not a very sound fix. The way we fixed the crash in the official SDK is to only attempt to set the clock and timezone on a Control Hub, which is the only place it ever worked anyway.

**Comment by Windwoes** [comment]
SDK issue of interest: https://github.com/FIRST-Tech-Challenge/FtcRobotController/issues/119

**Comment by eggonlea** [comment]
Yes, the RC app isn't a system one so it's not allowed to set it. Thx for providing more details!

**Pull request closed without merging**
